apiVersion: v1
kind: Template
labels:
  template: quay-dockerconfig-secret-template
metadata:
  annotations:
    description: quay-dockerconfig-secret-template
  name: quay-dockerconfig-secret-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${OCP_OBJECT_NAME}
  type: kubernetes.io/dockerconfigjson
  stringData:
    .dockerconfigjson: '{"auths": {"quay.io": {"auth": "${TOKEN}","email": ""}}}'

parameters:
- name: OCP_OBJECT_NAME
  displayName: Secret name
  required: true
- name: TOKEN
  displayName: Registry access token
  required: true
