apiVersion: v1
kind: Template
labels:
  template: iamp-spring-app-template
metadata:
  annotations:
    description: iamp-spring-app-template
  name: iamp-spring-app-template
objects:
- apiVersion: v1
  kind: ConfigMap
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${OCP_OBJECT_NAME}
  data:
    bootstrap.properties: |-
      ## =========================================================
      ##              Service
      ## =========================================================
      spring.application.name=${APP_NAME}
      spring.profiles.active=${APP_PROFILE}
      
      
      ## =========================================================
      ##              Config Server
      ## =========================================================
      spring.cloud.config.uri=${CONFIG_SERVER_URI}
      spring.cloud.config.fail-fast=true
      spring.cloud.config.label=${CONFIGS_BRANCH}
      
      ## Disable config health check
      health.config.enabled=false
      
      ## Cache health check response for 1 hour (in milliseconds)
      #health.config.time-to-live=3600000

- apiVersion: v1
  kind: Service
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${OCP_OBJECT_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: mgmt
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      name: ${OCP_OBJECT_NAME}
    sessionAffinity: None
    type: ClusterIP
    
- apiVersion: v1
  kind: DeploymentConfig
  labels:
    app: ${APP_NAME}
  metadata:
    name: ${OCP_OBJECT_NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      name: ${OCP_OBJECT_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${OCP_OBJECT_NAME}
      spec:
        containers:
          - name: ${OCP_OBJECT_NAME}
            image: ${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            env:
              - name: JAVA_OPTIONS
                value: "${JAVA_OPTIONS}"
              - name: NAMESPACE
                value: "${NAMESPACE}"
              - name: INFO_PLATFORM_NAMESPACE
                value: "${NAMESPACE}"
              - name: INFO_PLATFORM_TYPE
                value: "OpenShift"
              - name: INFO_DEPLOYMENT_TYPE
                value: "${DEPLOYMENT_TYPE}"
              - name: INFO_DEPLOYMENT_TAG
                value: "${DEPLOYMENT_TAG}"
            capabilities: {}            
            ports:
              - containerPort: 8080
                name: "http"
                protocol: "TCP"
              - containerPort: 8081
                name: "mgmt"
                protocol: "TCP"
            livenessProbe:
              httpGet:
                path: "/actuator/health"
                port: 8081
              initialDelaySeconds: 180
            readinessProbe:
              httpGet:
                path: "/actuator/health"
                port: 8081
              initialDelaySeconds: 10
            resources:
              requests:
                cpu: ${{CPU_REQUEST}}
                memory: ${MEMORY_REQUEST}
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
            volumeMounts:
              - mountPath: /deployments/config
                name: iamp-service-config
          
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
          - name: iamp-service-config
            configMap:
              name: ${OCP_OBJECT_NAME}

    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - ${OCP_OBJECT_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${IMAGE_TAG}
      type: ImageChange

parameters:
- description: The application name.
  displayName: Application Name
  name: APP_NAME
  required: true
- description: The application profile.
  displayName: Application profile
  name: APP_PROFILE
  required: true
- description: The application namespace.
  displayName: Application namespace
  name: NAMESPACE
  required: true
- description: The OpenShift DC name.
  displayName: OpenShift DC name
  name: OCP_OBJECT_NAME
  required: true
- description: replicas.
  displayName: Replicas
  name: REPLICAS
  value: "1"
- description: Minimum amount of memory to reserve for the container.
  displayName: Memory Request
  name: MEMORY_REQUEST
  value: 256Mi
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi
- description: Minimum amount of CPU to reserve for the container.
  displayName: CPU Request
  name: CPU_REQUEST
  value: 50m
- description: Maximum amount of CPU the container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  value: 500m
- description: JVM Options.
  displayName: JVM Options
  name: JAVA_OPTIONS
  value: "-XshowSettings:vm -Xms200m -Xmx450m"
- description: Image name.
  displayName: Image name
  name: IMAGE_NAME
  required: true
- description: Image tag.
  displayName: Image tag
  name: IMAGE_TAG
  required: true
- name: DEPLOYMENT_TYPE
  value: ""
- name: DEPLOYMENT_TAG
  value: ""            
- description: Config server uri.
  displayName: Config server uri
  name: CONFIG_SERVER_URI
  value: "http://spring-config-server:8080"
- description: Config server label.
  displayName: Config server label
  name: CONFIGS_BRANCH
  required: true